### ISSUE TITLE
Document the fate of Banned.h

### ISSUE THREAD

**Issue by ebaklund** [x509cert/banned#1]
Hi,
banned.h from Microsoft has been a appreciated tool in context of improving code quality and security.
This year, banned.h disappeared from Microsoft download pages but cropped up here.
It would be nice to see a few words in the README.md about the fate of banned.h, the cases banned.h should continued to be used, and when it should not be used.
Presumably Microsoft have some replacements tools?
it has been suggested at https://stackoverflow.com/questions/46212482/is-banned-h-alive
that _CRT_SECURE_NO_WARNINGS has taken over for banned.h.
It would be nice if such a claim could be commented on and from which compiler versions that claim may be true.

Kind regards,
Eriik

**Comment by x509cert** [comment]
Hey Eriik - I just saw this... please accept my apologies... when I get a moment, I will update the readme with more info about the history and future of the header. clearly, it's not rocket science, but it is certainly a useful 'backstop' :)

**Comment by ebaklund** [comment]
Hi,

Many thanks for your updating the readme with useful information.
I read from this that banned.h is still considered a useful tool that leverages various "security" features from the compiler. 

Kind regards,
Erik

**Comment by WebDancer69** [comment]
@x509cert What is the difference / benefit of using `banned.h` instead of `dontuse.h` from the Windows SDK?

**Comment by x509cert** [comment]
@webdancer69 they are essentially the same. Banned.h had been around for a longer time, however, and it's a requirement at MS. With that said, they really are almost identical. Oh, there is one big diff; banned.h supports gcc
