### ISSUE TITLE
Why is strlen removed?

### ISSUE THREAD

**Issue by oneiric** [x509cert/banned#2]
Hi Michael,
@x509cert 

We are going to update the banned.h to this latest one.
One of our concern is that strlen() is removed from this version. But our legacy recommended function is strlen_s().

Do you have more details for the comments in the header file?

"* 15-Jun-2012 - bryans   - Moved lstrlen to required banned; removed strlen, wcslen, _mbslen, _mbstrlen, StrLen from recommended banned"

Thanks,
Alex

**Comment by x509cert** [comment]
Good question - because we only found regressions and zero security benefit :)

**Comment by oneiric** [comment]
Thanks for your update, Michael.
