### ISSUE TITLE
Is this a Micorsoft official released banned.h?

### ISSUE THREAD

**Issue by zpgit** [x509cert/banned#3]
Microsoft does not provide a link to download banned.h anymore. 
Is this banned.h file official released by Microsoft?
I search `org:Microsoft banned.h` on github of all open source projects under Microsoft org. None of them using this version `banned.h`.

**Comment by x509cert** [comment]
It is … I was the original author and this is simply an updated version.

**Comment by zpgit** [comment]
Good to know this. Thank you @x509cert .
